resources:
  - name: src_repo
    type: GitRepo
    configuration:
      path: harshkumar1/python2
      gitProvider: hk_github_sample
pipelines:
  - name: pyhton_sample
    steps:
      - name: testReport
        type: Bash
        configuration:
          inputResources:
            - name: src_repo
        execution:
          onExecute:
            - ls
            - python -V
            - python3 -V
            - cd $res_src_repo_resourcePath
            - ls
            - pip install --upgrade pip #You are using pip version 8.1.2, however version 23.2.1 is available. Hence needs upgrade
            - pip --version
            - pip install pylint
            - pylint -version
            - pylint .
            - python hello-world.py
          onComplete:
            - echo "completed"
