resources:
  - name: src_repo
    type: GitRepo
    configuration:
      path: harshkumar1/python2
      gitProvider: hk_github_sample
pipelines:
  - name: pyhton_sample
    steps:
      - name: testReport
        type: Bash
        configuration:
          inputResources:
            - name: src_repo
        execution:
          onExecute:
            - cd $res_script_resourcePath
            - ls
            - python -V
            - python3 -V
            - cd $res_src_repo_resourcepath
            - ls
            - python hello-world.py
          onComplete:
            - echo "completed"
